export const effectPresets = {
  gemstone: [
    {
      id: "rose-diamond",
      label: "Rose Diamond",
      params: {
        colorA: "#dfb8cf",
        colorB: "#ee4b9d",
        colorC: "#547bc9",
        intensity: 0.63,
        facetScale: 28,
        contrast: 0.65,
        rim: 0.86,
        rimWidth: 0.36,
        textureScale: 0.74,
        textureAngle: -120,
        lightAngle: 107,
        satinEnabled: true,
        satinColor: "#f4dff2",
        satinStrength: 0.62,
        satinAngle: 24,
        satinDistance: 76,
        satinSize: 42,
        bevel: 0.99,
        bevelSize: 24.5,
      },
    },
    {
      id: "violet-crystal",
      label: "Violet Crystal",
      params: {
        colorA: "#cfc1e8",
        colorB: "#8252ed",
        colorC: "#466fd0",
        intensity: 0.66,
        facetScale: 24,
        contrast: 0.7,
        rim: 0.82,
        rimWidth: 0.38,
        textureScale: 0.78,
        textureAngle: -96,
        lightAngle: 96,
        satinEnabled: true,
        satinColor: "#eee2ff",
        satinStrength: 0.58,
        satinAngle: 30,
        satinDistance: 74,
        satinSize: 40,
        bevel: 0.9,
        bevelSize: 22,
      },
    },
    {
      id: "emerald-ice",
      label: "Emerald Ice",
      params: {
        colorA: "#b8dfcf",
        colorB: "#2fcf94",
        colorC: "#487fc4",
        intensity: 0.62,
        facetScale: 27,
        contrast: 0.66,
        rim: 0.74,
        rimWidth: 0.36,
        textureScale: 0.72,
        textureAngle: -132,
        lightAngle: 112,
        satinEnabled: true,
        satinColor: "#dcf7ed",
        satinStrength: 0.56,
        satinAngle: 20,
        satinDistance: 70,
        satinSize: 38,
        bevel: 0.84,
        bevelSize: 21,
      },
    },
  ],
  metal: [
    {
      id: "polished-silver",
      label: "Polished Silver",
      params: {
        colorA: "#bfc8d0",
        colorB: "#5f6873",
        colorC: "#0d1117",
        intensity: 0.56,
        facetScale: 34,
        contrast: 0.82,
        rim: 0.78,
        rimWidth: 0.34,
        textureScale: 0.68,
        textureAngle: -28,
        lightAngle: 92,
        satinEnabled: true,
        satinColor: "#cbd5dd",
        satinStrength: 0.66,
        satinAngle: 24,
        satinDistance: 82,
        satinSize: 44,
        bevel: 1.04,
        bevelSize: 26,
      },
    },
    {
      id: "warm-gold",
      label: "Warm Gold",
      params: {
        colorA: "#d2af66",
        colorB: "#d79228",
        colorC: "#5a3310",
        intensity: 0.68,
        facetScale: 32,
        contrast: 0.78,
        rim: 0.76,
        rimWidth: 0.34,
        textureScale: 0.72,
        textureAngle: -80,
        lightAngle: 104,
        satinEnabled: true,
        satinColor: "#f2dfa6",
        satinStrength: 0.52,
        satinAngle: 20,
        satinDistance: 78,
        satinSize: 44,
        bevel: 0.98,
        bevelSize: 24,
      },
    },
    {
      id: "pink-chrome",
      label: "Pink Chrome",
      params: {
        colorA: "#d9b7d5",
        colorB: "#f36ca4",
        colorC: "#5a4fb4",
        intensity: 0.66,
        facetScale: 36,
        contrast: 0.72,
        rim: 0.8,
        rimWidth: 0.36,
        textureScale: 0.76,
        textureAngle: -110,
        lightAngle: 100,
        satinEnabled: true,
        satinColor: "#f3dff1",
        satinStrength: 0.56,
        satinAngle: 26,
        satinDistance: 80,
        satinSize: 44,
        bevel: 0.94,
        bevelSize: 23,
      },
    },
  ],
};

export const paramSchema = [
  { key: "colorA", label: "Highlight", type: "color" },
  { key: "colorB", label: "Mid color", type: "color" },
  { key: "colorC", label: "Shadow color", type: "color" },
  { key: "intensity", label: "Intensity", type: "range", min: 0, max: 1.5, step: 0.01 },
  { key: "contrast", label: "Contrast", type: "range", min: 0, max: 1.5, step: 0.01 },
  { key: "rim", label: "Inner glow brightness", type: "range", min: 0, max: 1.5, step: 0.01 },
  { key: "rimWidth", label: "Inner glow width", type: "range", min: 0.15, max: 3, step: 0.01 },
  { key: "textureScale", label: "Texture scale", type: "range", min: 0.5, max: 6, step: 0.01 },
  { key: "textureAngle", label: "Texture angle", type: "range", min: -180, max: 180, step: 1 },
  { key: "lightAngle", label: "Light angle", type: "range", min: -180, max: 180, step: 1 },
  { key: "bevel", label: "Bevel", type: "range", min: 0, max: 1.5, step: 0.01 },
  { key: "bevelSize", label: "Bevel size", type: "range", min: 0.5, max: 48, step: 0.1 },
  { key: "satinEnabled", label: "Satin", type: "checkbox" },
  { key: "satinColor", label: "Satin color", type: "color" },
  { key: "satinStrength", label: "Satin gloss", type: "range", min: 0, max: 1, step: 0.01 },
  { key: "satinAngle", label: "Satin angle", type: "range", min: -180, max: 180, step: 1 },
  { key: "satinDistance", label: "Satin distance", type: "range", min: 0, max: 240, step: 1 },
  { key: "satinSize", label: "Satin size", type: "range", min: 1, max: 140, step: 1 },
];

export function getDefaultParams(effectName) {
  return { ...effectPresets[effectName][0].params };
}
